on:
  workflow_dispatch:

jobs:
  run_testing_suites:
    name: Custom Web Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Run tests
        uses: ./.github/custom
